### ISSUE TITLE
Question on back button functionality

### ISSUE THREAD

**Issue by alanontheweb** [terwanerik/AjaxPageParser#2]
I'm using your awesome script to target NOT just the main menu, but links inside the content area that would not be persistent across pages. I'm not sure how to use those kinds of links with the back button and the initialElement situation. I can capture the existing page URL using the Before function, but how do I pass that back to your script? Here's what I got working so far - 

```
$(function(){ 
    $('a[href$=".html"]:not([href*="://"],[target="_blank"],[href^="#"],[href^="mailto:"]), a[href^="'+location.protocol+'//'+location.hostname+'"]').pageParser({
        container:$('.page'),
        initialElement: $(".backURL"),
        parseElement: ".ajax-content",
        before: function(){
            // $(".loader").show();
            // backURL = window.location.href;
            // console.log(backURL);
        },
        finished: function(){

            slickInit();
            inPageNavInit();
            tablesInit();



        },
        error: function(){
            alert('Whoops, something went wrong.');
        }
    });
});
```

Thanks you!

**Comment by terwanerik** [comment]
You do not have to pass a initialElement for every call, it's the element (usually a menu item) that is in it's active state; say you are on the contact page, than the nav probably looks something like this:

```
<nav>
  <a href="/contact" class='active'>..</a>
  ..rest of the menu
</nav>
```

Than you can pass `$("nav a.active")` as the initialElement, that way the history is being popped the best way possible.

If you click on a link that is not in the menu, but somewhere in the content, and the page that link leads to has no link to itself (like the <a href="contact">, which is also on the contact page, in the menu) its no big deal, just skip the initialElement in that case. The script keeps on working.

**Comment by alanontheweb** [comment]
Looks like something got cut out of your example, but I think I understand what you're saying. What I'm trying to do right now is run the script inside of itself to AJAXify links that are not in the nav, but have been pulled into the page inside the the new content region by your script. 

So in your example, from **index.html**, I click on **contact.html**, pulling in the contact content region. Somewhere in the middle of this content region, there is a link to **services.html**. I want that link to also run pageParser and pull in **services.html.** And then I want the browser back button to return to **contact.html**. Is that possible? I have to update the menu script to add/remove the "active" class but just wanted to confirm.

```
$(function() {
        $('a:regex(href,^(.*\.(?=(htm|html)))?[^.]*$)').not('.no-scroll a, a.no-scroll, .tabs a, .mfpopup').not('[target="_blank"]').not('[href^="#"]').not('[href*="://"]').not('[href^="mailto:"], a[href^="' + location.protocol + '//' + location.hostname + '"]').pageParser({
            container: $('.page'),
                        initialElement: $("nav a.active"),
            parseElement: ".ajax-content",
            before: function() {
                // $(".loader").show();
            },
            finished: function() {
                  //initialize other scripts again

                $('.ajax-content a:regex(href,^(.*\.(?=(htm|html)$))?[^.]*$)').not('.no-scroll a, a.no-scroll, .tabs a, .mfpopup').not('[target="_blank"]').not('[href^="#"]').not('[href*="://"]').not('[href^="mailto:"], a[href^="' + location.protocol + '//' + location.hostname + '"]').pageParser({
                container:$('.page'),
                parseElement: ".ajax-content",
                });



            },
            error: function() {
                alert('Whoops, something went wrong.');
            }
        });
    });

```
